### ISSUE TITLE
[Android] ProductCreateActivity + ProductDetailActivity

### ISSUE THREAD

**Issue by cloneisme** [wafflestudio18-5/team8-android#18]
### ProductCreateActivity
- Features
    - [x] LinearLayout
    - [ ] SelectCartegoryFragment
    - [x] Incoming intent function
- [ ]  User Story
- Estimated Time : 2.0 hour
### ProductDetailActivity
- Features
    - [x] ImageView
    - [x] RecyclerView for other user sell product
    - [x] Incoming intent function
- [ ]  User Story
- Estimated Time : 2.0 hour
---

### PR Due date : 12/5

**Comment by jusjinuk** [comment]
@flux1126 `ProductUserBuyActivity`, `ProductUserSellActivity`에서 Recyclerview product item layout 만드실 때 직접 만드시지 마시고 이 [커밋](https://github.com/wafflestudio18-5/team8-android/pull/22/commits/61b77f98c7066b40717739d150709c4c936bd5b0) 참고하셔서 만들어놓은 `item_product` layout 사용하시면 시간도 아끼고 좋을 것 같습니다! (혹시나 #22 PR 머지 이전에 작업하실까봐 말씀드립니다. 물론 작업하시기 전에 리뷰해주셔서 머지하면 더 좋습니다ㅋㅋ)
