### ISSUE TITLE
[Android] Explicify type for DataBindingUtil.setContentView

### ISSUE THREAD

**Issue by jusjinuk** [wafflestudio18-5/team8-android#34]
#### `setContentView` 관련 minor한 issue
기능적 문제 개선은 아닙니다.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/58197958/103340560-b628b300-4ac7-11eb-8cbd-10d8c41e4de0.png">

실행에는 문제가 없는데 위 사진과 같이 Android Studio에서 에러가 있다고 linting하는 것이 그 내용입니다(nitpick). 에러의 내용은 아래와 같습니다.
<img width="650" alt="image" src="https://user-images.githubusercontent.com/58197958/103340734-2a635680-4ac8-11eb-9357-4af85a77cbeb.png">
lazy하게 대입하여 런타임 이전에는 setContentView의 타입을 몰라 생기는 문제인 듯 합니다.

#### 해결 방향
```
        DataBindingUtil.setContentView(
            this,
            R.layout.activity_search
        ) as ActivitySearchBinding
```
와 같이 타입을 함께 명시해주면 해결이 됩니다. 연결된 PR 만들겠습니다!

**Comment by cloneisme** [comment]
앗... 제 불찰 때문에 고생시켜서 정말 죄송합니다. 먼저 알아챘으면 제가 바꿨을텐데, 이상하게 제 안드로이드 스튜디오가 발견을 못한 것 같습니다. 너무너무 감사드립니다. 👍
