### ISSUE TITLE
[Android] SharedPreference에 User Info 저장

### ISSUE THREAD

**Issue by cloneisme** [wafflestudio18-5/team8-android#44]
- Features
  - [ ] 로그인에 성공했을 때 저장
  - [ ] 로그아웃 할 때 삭제
- Estimated Time : 3 hours
- PR due date: 1/5

**Comment by flux1126** [comment]
오프라인 상태에서도 MyPage 기능이 동작하려면 user_id를 제외한 나머지 정보들도 필요한데, User Model을 만든 뒤 Serialize해서 SharedPreference에 저장하나요?
